config/routes.rb
Rails.application.routes.draw do

  
  post '/events/:id/join', to: 'events#join', as: 'join'
  post '/events/:id/leave', to: 'events#leave', as: 'leave'


  resources :events
  resources :activities 
  root to: 'pages#home'
  
  devise_for :user
  resources :users, :only => [:show, :edit, :update]
  resources :activities 


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/activity.rb
class Activity < ApplicationRecord
    has_many :eventactivities
    has_many :events, through: :eventactivities

    validates :name, presence: true 


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :eventusers
    has_many :eventactivities
    has_many :activities, through: :eventactivities
    has_many :users, through: :eventusers

    accepts_nested_attributes_for :activities

    def self.most_popular
        my_events = Event.all.sort_by{|event|event.users.count}
        top_events_array = my_events.reverse.first(3)
    end

    def self.most
        my_events = Event.all.sort_by{|event|event.users.count}
        top_events_array = my_events.reverse.first
    end




end

app/models/eventactivity.rb
class Eventactivity < ApplicationRecord
    belongs_to :activity
    belongs_to :event

end

app/models/eventuser.rb
class Eventuser < ApplicationRecord
    belongs_to :user
    belongs_to :event

    validates :user_id, uniqueness: {scope: :event_id}



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :eventusers
    has_many :events, through: :eventusers

def coolest_host
  Event.most_popular.users.first.name
end

  

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    def index
        @activities = Activity.all
    end

    def show
    @activity = Activity.find(params[:id])
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    @event = Event.find(params[:id])
    #byebug
  end

  # GET /events/new
  def new
    @event = Event.new
    2.times {@event.activities.build}
  end

  def join
    @event = Event.find(params[:id])
    
    Eventuser.create(user: current_user, event: @event)
    #@event.users << current_user
    redirect_to event_path(@event)
    
  end

  def leave
    @event = Event.find(params[:id])
    if @event.users.include?(current_user)
      delete_user = @event.users.find(current_user.id)
      @event.users.delete(delete_user)
      redirect_to event_path(@event)
    else
      redirect_to event_path(@event)
    end
    
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    @event.users << current_user 
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
    
    @event.activities = []

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :location, :time, activities_attributes: [:name])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @user = User.find(params[:id])
    end

    def edit 
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params(:name, :age, :location))
        redirect_to user_path(@user)
    end



    def user_params(*args)
        params.require(:user).permit(*args)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/index.html.erb
<h1> Activities</h1> 

<%@activities.each do |activity|%>
  <div class="col-sm-6">
    <div class="card text-white bg-dark mb-3" style="width: 15rem;">
      <div class="card-body">
        <h5 class="card-title"><%=activity.name.capitalize%></h5>
        <a href="/activities/<%=activity.id%>" class="btn btn-primary"> Events </a>
      </div>
    </div>
  </div>
  <br>
<% end %>

app/views/activities/show.html.erb
<h1> <%= @activity.name.capitalize %></h1> 

<h3> Here are some groups related events: </h3>
<br>
<% activity_events = @activity.events.uniq %>
<% activity_events.each do |event| %>
  <div class="col-sm-6">
    <div class="card text-white bg-dark mb-3" style="width: 50rem;">
      <div class="card-body">
        <h5 class="card-title"><%=event.name.capitalize%></h5>
        <p class="card-text"><%=event.location.capitalize%></p>
        <p class="card-text"><%=event.time%></p>
        <a href="/events/<%=event.id%>" class="btn btn-primary">Details</a>
      </div>
    </div>
  </div>
  <br>
<% end %>


<%= link_to "Back", root_path %>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.datetime_select :time %>
  </div>

  <div class="field">
  <%= form.fields_for :activities do |activity_form| %>
    <%= activity_form.label :activity_name %>
    <%= activity_form.text_field :name %>
  <% end %> 
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<h1>All Current Events</h1>
<br>

<% @events.each do |event| %>
  <div class="col-sm-6">
    <div class="card text-white bg-dark mb-3" style="width: 50rem;">
      <div class="card-body">
        <h5 class="card-title"><%=event.name.capitalize%></h5>
        <p class="card-text"><%=event.location.capitalize%></p>
        <p class="card-text"><%=event.time%></p>
        <a href="/events/<%=event.id%>" class="btn btn-primary">Details</a>
      </div>
    </div>
  </div>
  <br>
<% end %>

<br>

<%= link_to 'New Event', new_event_path %>
<br>
<%= link_to "Sign out", destroy_user_session_path, method: :delete  %>
<br>
<%= link_to "Back", root_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time %>
</p>
<br>
<p>
<strong> People Attending: </strong> 
</p>

<% current_event = @event.users %>

<%current_event.each do |user|  %>
  <%= user.name %>
  <br>
<% end %>

<br>

<h3> Event Description: </h3>
<% @event.activities.each do |activity|  %>
  <%= activity.name %>
  <br>
<% end %>
<br>

<% if @event.users.include?(current_user) %>
  <%= button_to 'leave', leave_path %>
<% else %>
  <%= button_to 'join', join_path %>
<% end %>


<br>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<h1 class="text-center"><%=link_to "EVENTFINDER", root_path%></h1>
<h5><% if current_user %>
<div class= "text-left"><%=link_to "Sign out", destroy_user_session_path, method: :delete %></div>
<div class= "text-left"><%=link_to 'Profile', current_user %> </div>
<%else %>
<div class= "text-left" class= "text-center"><%=link_to "Sign up", new_user_registration_path %></div>
<div class= "text-left" class= "text-center"><%=link_to "Sign in", new_user_session_path %></div>
<%end%> </h5>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<%# events %>
<div class="collapse navbar-collapse"></div> 
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/events">Events <span class="sr-only">(current)</span></a>
      </li>
      <%# Activities %>
      <li class="nav-item">
        <a class="nav-link" href="/activities">Activities</a> 
      </li>
      <% if current_user %>
      <%# User Profile %>
       <li class="nav-item">
        <a class="nav-link" href="/users/<%=current_user.id%>">User profile</a> 
      </li>

      <%# User edit %>
       <li class="nav-item">
        <a class="nav-link" href="/users/<%=current_user.id%>/edit">Edit user</a> 
      </li>
      <%# User dropdown %>
      
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/users/<%=current_user.id%>">Profile</a>
          <a class="dropdown-item" href="/users/<%=current_user.id%>/edit">Edit Profile</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<% else %>
<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="drop" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          User
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/user/sign_in">Sign in </a>
          <a class="dropdown-item" href="/users/<%=current_user%>/edit"></a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<%end%>


  <head>

<title>Project2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
  <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-3">
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>

  
  
  <%# <% if current_user %>
<%# <div class= "text-center"><%=link_to "Sign out", destroy_user_session_path, method: :delete %></div>
<%# <div class= "text-center"><%=link_to 'Profile', current_user %> 
<%# <%else %>
<%# <div class= "align-bottom" class= "text-center"><%=link_to "Sign up", new_user_registration_path %></div> 
<%# <div class= "align-bottom" class= "text-center"><%=link_to "Sign in", new_user_session_path %></div> 
<%# <%end  %> 
</html>

app/views/pages/home.html.erb
 <% if current_user %>
 <% if current_user.name  %>

<h1> Our most popular events: <%=Event.most.users.first.name%> </h1>

<h1> Our most popular events: </h1>

<%Event.most_popular.each do |event|%>
  <div class="col-sm-6" >
    <div class="card text-white bg-dark mb-3" style="width: 50rem;">
        <div class="card-body">
            <h5 class="card-title"><%=event.name.capitalize%></h5>
            <p class="card-text"><%=event.location.capitalize%></p>
            <p class="card-text"><%=event.time%></p>
            <a href="/events/<%=event.id%>" class="btn btn-primary">Details</a>
      </div>
    </div>
  </div>
<%end%>





 <% else %>
 <p><h2><%= link_to "Please before continue complete your profile", edit_user_path(current_user)%></h2></p>
  <% end %>
 <% else %>
  <%end%>

app/views/users/edit.html.erb
<h1> Edit your profile</h1>

<%= form_for(@user) do |f| %>
  <label> Name:</label><br>
  <%= f.text_field :name %><br>
  <label> Email:</label><br>
  <%= f.email_field :email %><br>
  <label> Age:</label><br>
  <%= f.number_field :age %><br>
  <label> Location:</label><br>
  <%= f.text_field :location %><br>
   <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1> Hello  <%= @user.name %></h1> 
<ul>
<h3> Your age is: <%= @user.age %>   </h3> 
<h3> Your current location is: <%= @user.location %> </h3> 
<h3> Your current events are: </h3>
<% user_events = @user.events.uniq %>
<% user_events.each do |event| %>
    <h4><li><%= link_to event.name, event_path(event) %></li></h4>  
<% end %>
</ul>


<%= link_to "Back", root_path %>
<%= link_to "Edit Profile", edit_user_path(@user) %>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>